vim.pack.add({
    'https://github.com/stevearc/oil.nvim',
    'https://github.com/everviolet/nvim',
    'https://github.com/kdheepak/lazygit.nvim',
    'https://github.com/nvim-mini/mini.pick',
    'https://github.com/nvim-mini/mini.icons',
    'https://github.com/nvim-mini/mini.files',
    'https://github.com/nvim-mini/mini-git',
    'https://github.com/nvim-mini/mini.comment',
    'https://github.com/nvim-mini/mini.pairs',
    'https://github.com/nvim-mini/mini.surround',
    'https://github.com/nvim-mini/mini.splitjoin',
    'https://github.com/nvim-lualine/lualine.nvim',
    'https://github.com/saghen/blink.cmp',
    'https://github.com/EdenEast/nightfox.nvim',
    'https://github.com/webhooked/kanso.nvim',
    'https://github.com/neovim/nvim-lspconfig',
    'https://github.com/mason-org/mason.nvim',
    'https://github.com/mason-org/mason-lspconfig.nvim',
    'https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim',
    'https://github.com/nvim-treesitter/nvim-treesitter',
    'https://github.com/tronikelis/ts-autotag.nvim',
    'https://github.com/folke/todo-comments.nvim',
})

--other plugins that is quite long
require('plugins.oil')
require('plugins.blink')
require('plugins.lspconfig')
require('plugins.colorscheme')
require('plugins.lualine')
require('plugins.mason')
require('plugins.mini.general')
require('plugins.mini.pick')
require('plugins.mini.files')
require('plugins.treesitter')
require('plugins.todo-comments')
require('plugins.lazygit')
-- require('plugins.rosyln')
